# RoboSat Configuration
# For syntax see: https://github.com/toml-lang/toml#table-of-contents

[dataset]
  # The slippy map dataset's base directory.
  path = '~/rsp/dataset'

[classes]
  # Human representation for classes.
  titles = ['background', 'building']

  # Color map for visualization and representing classes in masks.
  # Note: available colors are either CSS3 colors names or #RRGGBB hexadecimal representation.
  colors  = ['white', 'deeppink']


# Channels configuration let your indicate wich dataset sub-directory and bands to take as input
# You could so, add several channels blocks to compose your input Tensor. Orders are meaningful.
[[channels]]
  sub = "images"
  bands = [1,2,3]


# Model specific attributes.
[model]

  # Batch size for training.
  batch_size = 8

  # Image side size in pixels.
  image_size = 512

  # Total number of epochs to train for.
  epochs     = 20

  # Learning rate for the optimizer.
  lr         = 0.000025

  # Weight decay l2 penalty for the optimizer
  decay      = 0.0

  # Loss function name (e.g 'Lovasz', 'mIoU' or 'CrossEntropy')
  loss = 'Lovasz'

  # Data augmentation, Flip or Rotate probability
  data_augmentation = 0.75

  # Use ImageNet weights pretraining
  pretrained = true
