# Configuration related to a specific dataset.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents


# Dataset specific common attributes.
[common]

  # The slippy map dataset's base directory.
  dataset = '/tmp/slippy-map-dir/'

  # Human representation for classes.
  classes = ['background', 'parking']

  # Color map for visualization and representing classes in masks.
  # Note: available colors can be found in `robosat/colors.py`
  colors  = ['denim', 'orange']

  # Input Tensor is composed by several images bands
  # Channels configuration let your indicate wich dataset sub-directory and band are concerned
  # Order is meaningful, syntax is: directory_name:band_number (1-n notation)
  channels = ['images:1', 'images:2', 'images:3']


# Dataset specific class weights computes on the training data.
# Needed by 'mIoU' and 'CrossEntropy' losses to deal with unbalanced classes.
# Note: use `./rs weights -h` to compute these for new datasets.
[weights]
  values = [1.6248, 5.762827]
