# Configuration related to a specific dataset.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents


# Dataset specific common attributes.
[common]

  # The slippy map dataset's base directory.
  dataset = '/tmp/robosat/'

  # Human representation for classes.
  classes = ['background', 'building']

  # Color map for visualization and representing classes in masks.
  # Note: available colors are either CSS3 colors names or #RRGGBB hexadecimal representation.
  colors  = ['white', 'deeppink']

# Channels configuration let your indicate wich dataset sub-directory and bands to take as input
# You could so, add several channels blocks to compose your input Tensor. Orders are meaningful.
[[channels]]
sub = "images"
bands = [1,2,3]
