# Configuration related to a specific model.
# For syntax see: https://github.com/toml-lang/toml#table-of-contents


# Model specific common attributes.
[common]

  # Batch size for training.
  batch_size = 8

  # Image side size in pixels.
  image_size = 512


# Model specific optimization parameters.
[opt]

  # Total number of epochs to train for.
  epochs     = 100

  # Learning rate for the optimizer.
  lr         = 0.000025

  # Weight decay l2 penalty for the optimizer
  decay      = 0.0

  # Loss function name (e.g 'Lovasz' or 'mIoU')
  loss = 'Lovasz'

  # Data augmentation, Flip or Rotate probability
  data_augmentation = 0.75

  # Use ImageNet weights pretraining
  pretrained = true
